name: Generate Contribution Snake Animation


on:

  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

 
  push:
    branches:
      - main
    paths:
      - '.github/workflows/snake.yml'


jobs:
  generate:
   
    permissions:
      contents: write
    
    
    runs-on: ubuntu-latest
    
   
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

  
    timeout-minutes: 5

    
    steps:
    
      - name: Generate snake.svg from user contributions
        uses: Platane/snk/svg-only@v3
        with:
         
          github_user_name: ${{ github.repository_owner }}
          
        
          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-3d.svg?palette=github-dark&color_snake=purple

     
      - name: Push generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
        
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}